### ISSUE TITLE
done function with parsedJson

### ISSUE THREAD

**Issue by JuanCaicedo** [RonB/angular-oboe#10]
The Oboe API offers a way to have add a listener on `done` that fires with the full response ([docs](http://oboejs.com/api#done-event)). 

Is it possible to do this with angular-oboe? Does either of the `done` that you instantiate the loading with, or the first function passed to the promise make that possible? Both of these have no arguments in the Readme, so I wasn't sure if it was possible or not.

Thanks!

**Comment by RonB** [comment]
Hi Juan,
This is already implemented. To listen to the 'done' event you pass a done function to the Oboe stream. From the docs:

done:function
Callback function which is called when the stream ends.

    angular.module('MyApp')
    .controller(['$scope', 'Oboe', function($scope, Oboe) {
        $scope.myData = [];
        Oboe({
            url: '/api/myData',
            pattern: '{index}',
            start: function(stream) {
                // handle to the stream
                $scope.stream = stream;
                $scope.status = 'started';
            },
            done: function() {
                $scope.status = 'done';
            }
        }).then(function() {
            // never called
        }, function(error) {
            // handle errors
        }, function(node) {
            // node received
            $scope.myData.push(node);
            if($scope.myData.length === 1000) {
                $scope.stream.abort();
                alert('The maximum of one thousand records reached');
            }
        });
    }]);

It cannot be done by passing a function to the promise which is returned because the first function never is called and the second function is called when an error occurs.

**Comment by JuanCaicedo** [comment]
Hey @RonB, I think maybe my question wasn't clear. In Oboe, the done listener takes an argument, `parsedJSON`. I'm not able to tell if your implementations allows for that. This is pretty useful because the node listeners are able to alter the data that is being parsed out. Also, I think this will address the problem that @erolg is seeing in #9 and in jimhigson/oboe.js#83

**Comment by RonB** [comment]
@JuanCaicedo 
I have reopened this issue to make sure the api matches the Oboe.js api for the done event. The parsedJSON is returned and the done function is called every time the Oboe stream fires it. The promise is only resolved once, after the first done event.
Would you be willing to test this feature? Thanks.

**Comment by erolg** [comment]
Hey Ronald,

I will test tomorrow and update this comment.Thank you :)

**Comment by JuanCaicedo** [comment]
I think @erolg is in the best place to do that since he already has some code set up. Thanks for looking at this @RonB!

**Comment by RonB** [comment]
@erolg Did you have any chance to test the modification? I will close the issue now. If there still is a problem than I can reopen this issue.
