### ISSUE TITLE
oboe parse json array memstream

### ISSUE THREAD

**Issue by atul550** [RonB/angular-oboe#14]
Not able to parse a json array shared by c# code in memstream.

the format is given below. we are able to get buffered string but how to pass pattern to oboe function not able to figure it out.

Please help.

find structure, in done method we are getting response as below.

Object__identity: null_buffer: Array[5283] length: 5283__proto__: Array[0]_capacity: 5283_expandable: false_exposable: false_isOpen: true_length: 5283_origin: 0_position: 0_writable: true__proto__: Object
filterTransactionController.js:148 

finished loading.....

**Comment by RonB** [comment]
Can you please enclose your structure in code tags so I can see the exact format, and please add which part of the json you want to extract? You can also send me the json file via email, ronb.brein@gmail.com.

**Comment by atul550** [comment]
Thanks Ron, For the quick help.

We are changing our response type to gzip to json. 
If we find any difficulty, in accessing data will get back to you.

**Comment by RonB** [comment]
Ok fine. If you need any assistance I'm glad to help. I will close the issue for now.
