### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by oswald0071** [RonB/angular-oboe#16]
Hi Ron

I wanted to try out your component with my angular 5 app. But, there's a compiler warning and it not works at all.

my npm list spoke out the following:
```
npm ERR! peer dep missing: @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0, required by codelyzer@3.2.2
npm ERR! peer dep missing: @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0, required by codelyzer@3.2.2
 @ ./src/app/app.module.ts
```

Are you planning to make your component supporting angular 5?

Greetings Oswald

**Comment by RonB** [comment]
I'm sorry Oswald, I don't have the time right now but you should be able to port it to Angular 5.
