### ISSUE TITLE
Callback when request has finished

### ISSUE THREAD

**Issue by ArtworkAD** [RonB/angular-oboe#3]
@RonB ```Oboe({})``` seems to return the data directly. However is there a way to obtain a promise of the request? Basically I want to get notified when the stream ends. 

------

So I had a closer look at https://github.com/RonB/angular-oboe/blob/master/src/angular-oboe.js I think you are coupling data and service too much which leads to having less control over the stream. I would give the developer the control over the promise and prefer this behaviour:

````
angular.module('ngOboe', []).service('Oboe', [
	'OboeStream',
	function(OboeStream) {
		return function(params) {
			return OboeStream.search(params);
		};
	}
])

.factory('OboeStream', ['$q', function($q) {
	return {

		search: function(params) {

			var defer = $q.defer(),
				counter = 0,
				pagesize = params.pagesize || 100,
				page = [];

			oboe(params).start(function() {
				// do nothing or notify starting of download
			}).node(params.pattern, function(node) {
				defer.notify(node);
				oboe.drop;
			}).done(function(result) {
				defer.resolve(result);
			});
			return defer.promise;
		}
	};
}]);
```

The usage would be like this:
```
$scope.data = [];
Oboe({
  url: url,
  pattern: '*'
}).then(function(lastChunk){
  $scope.data.push(lastChunk);
}, function(reason){
  // some error occured
}, function(update){
  $scope.data.push(update);
});
```

What do you think?

**Comment by RonB** [comment]
@ArtworkAD Yes, returning the promise has its advantages, allthough it will complicate the usage a little. The developer needs a basic understanding of the $promise, but I like the idea.
In your example you don't use the paging functionality. That means that for every node the scope get's updated and the digest cycle will run. You want to control that behaviour to prevent the ui from going bananas.

**Comment by seiyria** [comment]
I definitely agree with this. I need to update a ng-table instance every time I get data from oboe to make it work as expected. I don't think it's unreasonable to provide a simple implementation and a promise implementation, that way people can use what they need to to get what they want.

**Comment by seiyria** [comment]
I've implemented this in [my fork](https://github.com/VersifitTechnologies/angular-oboe), if you'd like me to send up a PR, let me know.

**Comment by RonB** [comment]
I've updated the code and the docs a little. Thanks for this major improvement.

**Comment by seiyria** [comment]
https://github.com/RonB/angular-oboe/blob/master/src/angular-oboe.js#L25 Are you sure this shouldn't be `return oboe.drop`?

**Comment by RonB** [comment]
Agree. Sorry for this! Has been fixed.
