### ISSUE TITLE
Can you publish to npm?

### ISSUE THREAD

**Issue by riggerthegeek** [RonB/angular-oboe#6]
Pretty please?  I'm using Browserify and, whilst I can work with the bower package, I'd rather work with npm.

Thanks

**Comment by RonB** [comment]
Hi, i have published to NPM but am not sure wether the package.json suites your needs. Can you try?

**Comment by riggerthegeek** [comment]
I'm not sure it's been published correctly.  The only version in the [npm registry](http://registry.npmjs.org/angular-oboe) is v0.4.0.  The `package.json` and `bower.json` say that they're at v0.5.2

**Comment by RonB** [comment]
NPM repository udated to 0.5.3
